[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = {eth-sepolia = "https://eth-sepolia.g.alchemy.com/v2/94JQRFI8N4z_Tnte0RNk6", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/94JQRFI8N4z_Tnte0RNk6"}
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@ccip/contracts/=lib/ccip/contracts/src/v0.8/",
    "@chainlink/local/=lib/chainlink-local/"
]
FOUNDRY_DISABLE_NIGHTLY_WARNING = true
viaIR = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
